# Generated by Django 4.2.4 on 2023-08-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscripcion',
            new_name='Proyecto',
        ),
    ]
