# Generated by Django 4.2.4 on 2023-08-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_rename_suscripcion_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='proyecto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.proyecto'),
        ),
    ]
